# Generated by Django 2.2.7 on 2020-02-01 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloudlogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='logs',
            name='source',
            field=models.CharField(default='nginx', max_length=100),
            preserve_default=False,
        ),
    ]
